apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
spec:  
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-storage
            - name: NFS_SERVER
              value: 10.0.0.203
            - name: NFS_PATH
              value: /export/nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.0.0.203
            path: /export/nfs